services:
  - type: web
    name: calendar-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir Src api:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: CLERK_JWKS_URL
        sync: false
